format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
${custom.distrobox}\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "blue"
truncation_symbol = "…/"
repo_root_style= "yellow italic"
fish_style_pwd_dir_length = 4

[directory.substitutions]
"/run/media/rlacerda/Files_HDD" = "/Files_HDD"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
disabled = true

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[custom.distrobox]
command = "echo $CONTAINER_ID"
when = "test -n \"$CONTAINER_ID\""
format = "on [📦 $output](bold blue) "
