gui:
  branchColorPatterns:
    'main': 'blue'
    'develop': 'yellow'
    'hotfix/': 'red'
  authorColors:
    'Renato Lacerda': 'cyan'
    '*': 'red'
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - default
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red

disableStartupPopups: true

git: 
  mainBranches:
    - master
    - main
    - develop

keybinding:
  universal:
    quit: 'Q'
    quit-alt1: '<c-c>' # alternative/alias of quit
    return: '<c-q>' # return to previous menu, will quit if there's nowhere to return

os:
  Edit: 'nano'

notARepository: 'skip'
